name: Trigger auto deployment for fsm-designer-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/fsm-designer-app-AutoDeployTrigger-5788b19a-7bfc-4d47-9396-df65e18b4faf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FSMDESIGNERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FSMDESIGNERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FSMDESIGNERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUsername: ${{ secrets.FSMDESIGNERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FSMDESIGNERAPP_REGISTRY_PASSWORD }}
          containerAppName: fsm-designer-app
          resourceGroup: TobiCreations_group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
